workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    integrations:
      app_store_connect: PAGCRM
    environment:
      groups:
        - signing
      vars:
        APP_ID: 6762884165
      node: v22
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web
        script: npm run build
      - name: Capacitor sync
        script: npx cap sync ios
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files \
            "com.platonabramov.app" \
            --type IOS_APP_STORE \
            --create
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Set up Xcode settings
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_ID")
          NEW_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          cd ios/App
          agvtool new-version -all $NEW_BUILD_NUMBER
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --project "ios/App/App.xcodeproj" \
            --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true